export const CONNECTION_STATE = {}

CONNECTION_STATE.CLOSED = 'CLOSED'
CONNECTION_STATE.AWAITING_CONNECTION = 'AWAITING_CONNECTION'
CONNECTION_STATE.CHALLENGING = 'CHALLENGING'
CONNECTION_STATE.AWAITING_AUTHENTICATION = 'AWAITING_AUTHENTICATION'
CONNECTION_STATE.AUTHENTICATING = 'AUTHENTICATING'
CONNECTION_STATE.OPEN = 'OPEN'
CONNECTION_STATE.ERROR = 'ERROR'
CONNECTION_STATE.RECONNECTING = 'RECONNECTING'

export const RECORD_STATE = {}
RECORD_STATE.VOID = 0
RECORD_STATE.CLIENT = 1
RECORD_STATE.SERVER = 2
RECORD_STATE.STALE = 3
RECORD_STATE.PROVIDER = 4

export const RECORD_STATE_NAME = []
for (const [key, val] of Object.entries(RECORD_STATE)) {
  RECORD_STATE_NAME[val] = key
}

export const MESSAGE_SEPERATOR = String.fromCharCode(30) // ASCII Record Seperator 1E
export const MESSAGE_PART_SEPERATOR = String.fromCharCode(31) // ASCII Unit Separator 1F

export const TYPES = {}
TYPES.STRING = 'S'
TYPES.OBJECT = 'O'
TYPES.NUMBER = 'N'
TYPES.NULL = 'L'
TYPES.TRUE = 'T'
TYPES.FALSE = 'F'
TYPES.UNDEFINED = 'U'

export const TOPIC = {}
TOPIC.CONNECTION = 'C'
TOPIC.AUTH = 'A'
TOPIC.ERROR = 'X'
TOPIC.EVENT = 'E'
TOPIC.RECORD = 'R'
TOPIC.RPC = 'P'
TOPIC.PRIVATE = 'PRIVATE/'

export const EVENT = {}
EVENT.CONNECTION_ERROR = 'connectionError'
EVENT.CONNECTION_STATE_CHANGED = 'connectionStateChanged'
EVENT.CONNECTED = 'connected'
EVENT.MAX_RECONNECTION_ATTEMPTS_REACHED = 'MAX_RECONNECTION_ATTEMPTS_REACHED'
EVENT.CONNECTION_AUTHENTICATION_TIMEOUT = 'CONNECTION_AUTHENTICATION_TIMEOUT'
EVENT.NO_RPC_PROVIDER = 'NO_RPC_PROVIDER'
EVENT.RPC_ERROR = 'RPC_ERROR'
EVENT.TIMEOUT = 'TIMEOUT'
EVENT.UNSOLICITED_MESSAGE = 'UNSOLICITED_MESSAGE'
EVENT.MESSAGE_DENIED = 'MESSAGE_DENIED'
EVENT.NOT_CONNECTED = 'NOT_CONNECTED'
EVENT.MESSAGE_PARSE_ERROR = 'MESSAGE_PARSE_ERROR'
EVENT.NOT_AUTHENTICATED = 'NOT_AUTHENTICATED'
EVENT.MESSAGE_PERMISSION_ERROR = 'MESSAGE_PERMISSION_ERROR'
EVENT.LISTENER_EXISTS = 'LISTENER_EXISTS'
EVENT.PROVIDER_ERROR = 'PROVIDER_ERROR'
EVENT.CACHE_ERROR = 'CACHE_ERROR'
EVENT.UPDATE_ERROR = 'UPDATE_ERROR'
EVENT.USER_ERROR = 'USER_ERROR'
EVENT.REF_ERROR = 'REF_ERROR'
EVENT.PROVIDER_EXISTS = 'PROVIDER_EXISTS'
EVENT.NOT_LISTENING = 'NOT_LISTENING'
EVENT.NOT_PROVIDING = 'NOT_PROVIDING'
EVENT.LISTENER_ERROR = 'LISTENER_ERROR'
EVENT.TOO_MANY_AUTH_ATTEMPTS = 'TOO_MANY_AUTH_ATTEMPTS'
EVENT.IS_CLOSED = 'IS_CLOSED'
EVENT.RECORD_NOT_FOUND = 'RECORD_NOT_FOUND'
EVENT.NOT_SUBSCRIBED = 'NOT_SUBSCRIBED'

export const ACTIONS = {}
ACTIONS.PING = 'PI'
ACTIONS.PONG = 'PO'
ACTIONS.ACK = 'A'
ACTIONS.REDIRECT = 'RED'
ACTIONS.CHALLENGE = 'CH'
ACTIONS.CHALLENGE_RESPONSE = 'CHR'
ACTIONS.READ = 'R'
ACTIONS.UPDATE = 'U'
ACTIONS.SUBSCRIBE = 'S'
ACTIONS.SYNC = 'SY'
ACTIONS.UNSUBSCRIBE = 'US'
ACTIONS.SUBSCRIPTION_FOR_PATTERN_FOUND = 'SP'
ACTIONS.SUBSCRIPTION_FOR_PATTERN_REMOVED = 'SR'
ACTIONS.SUBSCRIPTION_HAS_PROVIDER = 'SH'
ACTIONS.LISTEN = 'L'
ACTIONS.UNLISTEN = 'UL'
ACTIONS.LISTEN_ACCEPT = 'LA'
ACTIONS.LISTEN_REJECT = 'LR'
ACTIONS.EVENT = 'EVT'
ACTIONS.ERROR = 'E'
ACTIONS.REQUEST = 'REQ'
ACTIONS.RESPONSE = 'RES'
ACTIONS.REJECTION = 'REJ'
